# Generated by Django 5.2.6 on 2025-09-29 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.CharField(max_length=300)),
                ('imagem', models.CharField(max_length=500)),
                ('capacidade', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('destaque', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=255)),
                ('fk_empresa_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.enterpriseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField()),
                ('fk_cliente_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='clients.clientprofile')),
                ('fk_evento_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('confianca_empresa', models.IntegerField(default=0)),
                ('comentario_geral', models.CharField(max_length=300)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_evaluation', to='clients.clientprofile')),
                ('fk_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_evaluation', to='companies.enterpriseprofile')),
                ('fk_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_evaluation', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAndCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fk_id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_and_category', to='events.category')),
                ('fk_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_and_category', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('INTEIRA', 'Inteira'), ('MEIA', 'Meia')], max_length=100)),
                ('valor_receber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_max_venda', models.IntegerField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('price_id', models.CharField(max_length=64)),
                ('fk_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAndHashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fk_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_and_hashtag', to='events.event')),
                ('fk_id_hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_and_hashtag', to='events.hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='SaleTickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField()),
                ('checkout_session_id', models.CharField(max_length=70)),
                ('clienteId_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='clients.clientprofile')),
                ('empresaId_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='companies.enterpriseprofile')),
            ],
        ),
    ]
