# Generated by Django 5.2.6 on 2025-09-14 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.CharField(max_length=300)),
                ('imagem', models.CharField(max_length=500)),
                ('capacidade', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('destaque', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=255)),
                ('fk_empresa_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.enterpriseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('confianca_empresa', models.IntegerField(default=0)),
                ('comentario_geral', models.CharField(max_length=300)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_evaluation', to='clients.clientprofile')),
                ('fk_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_evaluation', to='companies.enterpriseprofile')),
                ('fk_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_evaluation', to='events.event')),
            ],
        ),
    ]
