# Generated by Django 5.2.6 on 2025-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='valor_comprador',
            field=models.CharField(default='', max_length=12),
        ),
    ]
