# Generated by Django 5.2.6 on 2025-10-29 19:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventticket_valor_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome'),
        ),
    ]
