# Generated by Django 5.2.6 on 2025-12-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
