# Generated by Django 5.2.6 on 2025-09-29 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('INKLUABOTTLE', 'InkluaBottle'), ('BRACELET', 'Bracelet')], max_length=255)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('BLACK', 'Black')], max_length=255)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('BIG', 'Big')], max_length=255)),
                ('icon', models.CharField(choices=[('NOICON', 'No Icon'), ('EAR', 'Ear'), ('EYE', 'Eye'), ('SPEECHBUBBLE', 'Speech Bubble'), ('BRAIN', 'Brain'), ('WHEELCHAIR', 'Wheelchair'), ('STAR', 'Star'), ('GAMEPAD', 'Gamepad'), ('DIAMOND', 'Diamond'), ('HEART', 'Heart'), ('MUSIC', 'Music'), ('ACCESSIBILITY', 'Accessibility')], default='NoIcon', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='clients.clientprofile')),
            ],
        ),
    ]
