# Generated by Django 5.2.5 on 2025-09-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(choices=[('NOICON', 'No Icon'), ('EAR', 'Ear'), ('EYE', 'Eye'), ('SPEECHBUBBLE', 'Speech Bubble'), ('BRAIN', 'Brain'), ('WHEELCHAIR', 'Wheelchair'), ('STAR', 'Star'), ('GAMEPAD', 'Gamepad'), ('DIAMOND', 'Diamond'), ('HEART', 'Heart'), ('MUSIC', 'Music'), ('ACCESSIBILITY', 'Accessibility')], default='NoIcon', max_length=255),
        ),
    ]
