# Generated by Django 5.2.6 on 2025-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phrase',
            field=models.CharField(choices=[('NOPHRASE', 'No phrase'), ('FP', 'Personalized'), ('F1', 'Faça a diferença, inKlua!'), ('F2', 'Todos merecem viver grandes experiências'), ('F3', '#InklusaoParaTodos')], default='noPhrase', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='typografy',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('BRAILLE', 'Braille'), ('PIXELATED', 'Pixelated')], default='Standard', max_length=255),
        ),
    ]
