# Generated by Django 5.2.6 on 2025-11-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_phrase_product_typografy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='typografy',
            new_name='typography',
        ),
    ]
