# Generated by Django 5.2.6 on 2025-11-27 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientticket_salfk_id_vendae_and_more'),
        ('store', '0003_rename_typografy_product_typography'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_order_id', models.CharField(editable=False, max_length=255)),
                ('sale_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('status_start_date', models.DateTimeField()),
                ('status_finished_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='clients.clientprofile')),
            ],
        ),
    ]
