# Generated by Django 5.2.6 on 2025-12-06 16:45

import django.db.models.deletion
import store.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientticket_salfk_id_vendae_and_more'),
        ('store', '0003_rename_typografy_product_typography'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_order_id', models.CharField(editable=False, max_length=255)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_forecast', models.DateTimeField(default=store.models.one_week_from_now)),
                ('status', models.CharField(max_length=100)),
                ('status_start_date', models.DateTimeField(null=True)),
                ('status_finished_date', models.DateTimeField(null=True)),
                ('preparation', models.DateTimeField(null=True)),
                ('ready', models.DateTimeField(null=True)),
                ('delivered', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='clients.clientprofile')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.saleproduct')),
            ],
        ),
    ]
