# Generated by Django 5.2.6 on 2025-12-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_saleproduct_notificationstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstore',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='store.saleproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(choices=[('BAN', 'Ban'), ('EAR', 'Ear'), ('EYE', 'Eye'), ('MESSAGECIRCLE', 'Message Circle'), ('BRAIN', 'Brain'), ('ACCESSIBILITY', 'accessibility'), ('STAR', 'Star'), ('GAMEPAD', 'Gamepad'), ('GEM', 'Gem'), ('HEART', 'Heart'), ('MUSIC', 'Music')], default='NoIcon', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('INKLUABOTTLE', 'InkluaBottle'), ('INKLUABRACELET', 'Bracelet')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='phrase',
            field=models.CharField(choices=[('NOPHRASE', 'No phrase'), ('CUSTOM', 'Custom'), ('F1', 'Faça a diferença, inKlua!'), ('F2', 'Todos merecem viver grandes experiências'), ('F3', '#InklusaoParaTodos')], default='noPhrase', max_length=255),
        ),
    ]
