# Generated by Django 5.2.6 on 2025-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_notificationstore_sale_alter_product_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='position_table',
            field=models.IntegerField(null=True),
        ),
    ]
