# Generated by Django 5.2.6 on 2025-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_saleproduct_position_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colum', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
