services:
  db:
    image: postgres:15
    container_name: dbi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inkluaticket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backendp:
    build: .
    container_name: backendp
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inkluaticket
    depends_on:
      - db    

volumes:
  postgres_data: