# Generated by Django 5.2.6 on 2025-09-14 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('imagem', models.CharField(blank=True, max_length=15, null=True)),
                ('banner', models.CharField(blank=True, max_length=500, null=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('inklua_coins', models.IntegerField(default=0)),
                ('aceitaTermos', models.BooleanField(default=False)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disability_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fisica', models.BooleanField(default=False)),
                ('auditiva', models.BooleanField(default=False)),
                ('visual', models.BooleanField(default=False)),
                ('comunicativa', models.BooleanField(default=False)),
                ('cognitiva', models.BooleanField(default=False)),
                ('outra', models.BooleanField(default=False)),
                ('nao_possuo', models.BooleanField(default=False)),
                ('nao_comentar', models.BooleanField(default=False)),
                ('outra_texto', models.CharField(blank=True, max_length=300, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disability_type', to='clients.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateTimeField()),
                ('nome_evento', models.CharField(max_length=100)),
                ('local_evento', models.CharField(max_length=100)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='clients.clientprofile')),
                ('fk_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='companies.enterpriseprofile')),
            ],
        ),
    ]
