# Generated by Django 5.2.4 on 2025-08-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='imagem',
        ),
        migrations.AddField(
            model_name='client',
            name='aceitaTermos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='banner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='biografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='inklua_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='nome',
            field=models.CharField(default='AAAAAAAAAAAAAAAAAAAAAAAAAA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=319),
        ),
        migrations.CreateModel(
            name='Disability_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fisica', models.BooleanField(default=False)),
                ('auditiva', models.BooleanField(default=False)),
                ('visual', models.BooleanField(default=False)),
                ('comunicativa', models.BooleanField(default=False)),
                ('cognitiva', models.BooleanField(default=False)),
                ('outra', models.BooleanField(default=False)),
                ('nao_possuo', models.BooleanField(default=False)),
                ('nao_comentar', models.BooleanField(default=False)),
                ('outra_texto', models.CharField(blank=True, max_length=300, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disability_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_evento', models.DateTimeField()),
                ('nome_evento', models.CharField(max_length=100)),
                ('local_evento', models.CharField(max_length=100)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
                ('fk_id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='companies.enterprise')),
                ('fk_id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='events.event')),
            ],
        ),
    ]
