# Generated by Django 5.2.6 on 2025-09-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fk_id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='events.event'),
        ),
    ]
