# Generated by Django 5.2.6 on 2025-09-29 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientticket',
            name='fk_id_ingresso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ticket', to='events.eventticket'),
        ),
        migrations.AddField(
            model_name='clientticket',
            name='salfk_id_vendae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ticket', to='events.saletickets'),
        ),
        migrations.AddField(
            model_name='disability_type',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disability_type', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='fk_id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='fk_id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='companies.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='fk_id_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='events.event'),
        ),
        migrations.AddField(
            model_name='visualconfiguration',
            name='fk_id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.clientprofile'),
        ),
    ]
