# Generated by Django 5.2.6 on 2025-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientticket',
            name='status',
            field=models.CharField(default='INVÁLIDO', max_length=30),
        ),
    ]
