# Generated by Django 5.2.6 on 2025-11-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientticket_status'),
        ('events', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientticket',
            name='salfk_id_vendae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ticket_sale', to='events.saletickets'),
        ),
        migrations.AlterField(
            model_name='visualconfiguration',
            name='nome_select',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
