# Generated by Django 5.2.4 on 2025-08-25 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('FISICA', 'Fisica'), ('AUDITIVA', 'Auditiva'), ('VISUAL', 'Visual'), ('COMUNICATIVA', 'Comunicativa'), ('MOTORA', 'Motora'), ('COGNITIVA', 'Cognitiva')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Accessibility_Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estava_presente', models.BooleanField(default=False)),
                ('condicao', models.CharField(choices=[('EXCELENTE', 'Exelente'), ('PRECARIA', 'Precaria'), ('RAZOAVEL', 'Razoavel'), ('NAO_UTILIZEI', 'Não utilizei')], max_length=30)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_assessment', to='events.event_evaluation')),
                ('fk_id_tipo_acessibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_assessment', to='accessibility.accessibility_type')),
            ],
        ),
        migrations.CreateModel(
            name='Accessbility_Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fk_id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('fk_id_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.event')),
                ('fk_id_tipo_acessibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_registration', to='accessibility.accessibility_type')),
            ],
        ),
    ]
