# Generated by Django 5.2.6 on 2025-09-29 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessbility_Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Accessibility_Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estava_presente', models.BooleanField(default=False)),
                ('condicao', models.CharField(choices=[('EXCELENTE', 'Exelente'), ('PRECARIA', 'Precaria'), ('RAZOAVEL', 'Razoavel'), ('NAO_UTILIZEI', 'Não utilizei')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Accessibility_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('FISICA', 'Fisica'), ('AUDITIVA', 'Auditiva'), ('VISUAL', 'Visual'), ('COMUNICATIVA', 'Comunicativa'), ('MOTORA', 'Motora'), ('COGNITIVA', 'Cognitiva')], max_length=30)),
            ],
        ),
    ]
