# Generated by Django 5.2.6 on 2025-09-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessibility', '0001_initial'),
        ('clients', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessbility_registration',
            name='fk_id_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='accessbility_registration',
            name='fk_id_evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.event'),
        ),
        migrations.AddField(
            model_name='accessibility_assessment',
            name='avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_assessment', to='events.event_evaluation'),
        ),
        migrations.AddField(
            model_name='accessibility_assessment',
            name='fk_id_tipo_acessibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_assessment', to='accessibility.accessibility_type'),
        ),
        migrations.AddField(
            model_name='accessbility_registration',
            name='fk_id_tipo_acessibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_registration', to='accessibility.accessibility_type'),
        ),
    ]
