# Generated by Django 5.2.5 on 2025-09-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0002_alter_accessibility_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibility_type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
