# Generated by Django 5.2.4 on 2025-08-25 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=500)),
                ('banner', models.CharField(max_length=500)),
                ('sobre', models.TextField()),
                ('slug', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=319, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
                ('stripe_account_id', models.CharField(max_length=59)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
