# Generated by Django 5.2.6 on 2025-09-14 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=500, null=True)),
                ('banner', models.CharField(max_length=500, null=True)),
                ('sobre', models.TextField(null=True)),
                ('slug', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('stripe_account_id', models.CharField(max_length=59, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
