# Generated by Django 5.2.6 on 2025-09-29 19:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug_source'),
        ),
    ]
